[tool.poetry]
name = "mini-iso"
version = "0.1.0"
description = ""
authors = ["Jon Pearce <jonpea@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
